apiVersion: apps/v1
kind: Deployment
metadata:
  name: argoupdater
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argoupdater
  template:
    metadata:
      labels:
        app: argoupdater
    spec:
      containers:
      - image: docker.io/shinkiho/argoupdater:2.0
        name: argoupdater-container
        ports:
        - containerPort: 80
