apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argoupdater
spec:
  rules:
  - host:
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: argoupdater-svc
            port:
              number: 80
